# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    controller: 'App\Controller\Index'

xhrTest:
    path: /ajax
    methods: 'POST'
    controller: 'App\Controller\Ajax'

#########################################################################
# This is the section to the influencer bundle

influencer_login:
    path: /influencer/login
    methods: 'POST'
    controller: 'App\Influencer\Login\Controller\Login'

influencer_register:
    path: /influencer/register
    methods: 'POST'
    controller: 'App\Influencer\Register\Controller\Register'

influencer_validate_uid:
    path: /influencer/validate/uid
    methods: 'POST'
    controller: 'App\Influencer\UserIdValidation\Controller\UserIdValidate'

influencer_dashboard:
    path: /influencer/dashboard
    methods: 'POST'
    controller: 'App\Influencer\Dashboard\Controller\Dashboard'

influencer_campaign_recommendation:
    path: /influencer/campaign/recommendation
    methods: ['POST', 'GET']
    controller: 'App\Influencer\Campaign\Controller\Recommendation'

influencer_import_instagram:
    path: /influencer/import/instagram
    methods: 'POST'
    controller: 'App\Influencer\SocialMediaImport\Controller\Instagram'

#########################################################################
# This is the section to the influencer bundle

advertiser_login:
    path: /advertiser/login
    methods: 'POST'
    controller: 'App\Advertiser\Login\Controller\Login'

advertiser_register:
    path: /advertiser/register
    methods: 'POST'
    controller: 'App\Advertiser\Register\Controller\Register'