# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    controller: 'App\Influencer\Index\Controller\Index'

xhrTest:
    path: /ajax
    controller: 'App\Influencer\Index\Controller\Ajax'

#########################################################################
# This is the section to the influencer bundle

influencer_login:
    path: /influencer/login
    methods: 'POST'
    controller: 'App\Influencer\Login\Controller\Login'

influencer_register:
    path: /influencer/register
    methods: ['POST', 'OPTIONS']
    controller: 'App\Influencer\Register\Controller\Register'